/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pertemuan1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author v
 */
public class KreditMobil extends javax.swing.JFrame {
    
    DefaultTableModel tabModel;
    private Connection konek;
    private Statement stat;
    private ResultSet set;
    private PreparedStatement prestat;

    /**
     * Creates new form KreditMobil
     */
    public KreditMobil() {
        initComponents();
        String row[] = {"NAMA", "MOBIL", "HARGA", "LAMA ANGSUR", "BESAR ANGSUR", 
            "BUNGA", "TOTAL ANGSURAN"};
        tabModel = new DefaultTableModel(null, row);
        jTable1.setModel(tabModel);
        koneksiDatabase();
        tampilDatakeTabel();
    }
    
    public Connection koneksiDatabase(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver ditemukan");
            String url = "jdbc:mysql://localhost:3306/kredit";
            String user = "root";
            String pass = "";
            konek = DriverManager.getConnection(url,user,pass);
            System.out.println("Database terkoneksi");
        }catch(ClassNotFoundException e){
            System.out.println("Driver tidak ditemukan");
            System.exit(0);
        }catch(SQLException e){
            System.out.println("Koneksi database gagal");
        }
        return konek;
    }
    
    public void tampilDatakeTabel(){
        try{
            String sql = "select * from mobil";
            stat = konek.createStatement();
            set = stat.executeQuery(sql);
            while(set.next()){
                String nama = set.getString("nama");
                String mobil = set.getString("mobil");
                String harga = set.getString("harga");
                String lama = set.getString("lama");
                String besar = set.getString("besar");
                String bunga = set.getString("bunga");
                String total = set.getString("total");
                String data[] = {nama,mobil,harga,lama,besar,
                        bunga,total};
                tabModel.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    public void hapusPadaForm(){
        int row = tabModel.getRowCount();
        for (int a=0; a<row; a++){
            tabModel.removeRow(0);
        }
    }
    
    public void clear(){
        tfNama.setText(null);
        cmbMobil.setSelectedIndex(0);
        tfHarga.setText(null);
        bgLama.setSelected(null, rootPaneCheckingEnabled);
        tfAngsur.setText(null);
        tfBunga.setText(null);
        tfTotal.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLama = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        cmbMobil = new javax.swing.JComboBox();
        tfHarga = new javax.swing.JTextField();
        rb12 = new javax.swing.JRadioButton();
        rb24 = new javax.swing.JRadioButton();
        rb36 = new javax.swing.JRadioButton();
        tfAngsur = new javax.swing.JTextField();
        tfBunga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(97, 97, 97)
                .addComponent(btnUbah)
                .addGap(85, 85, 85)
                .addComponent(btnHapus)
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kredit Mobil");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mobil");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Lama Angsur");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Besar Angsur");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bunga");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total Angsuran");

        tfNama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cmbMobil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbMobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Mobil", "Avanza", "City", "Alphard" }));
        cmbMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMobilActionPerformed(evt);
            }
        });

        tfHarga.setEditable(false);
        tfHarga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        bgLama.add(rb12);
        rb12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb12.setText("12");
        rb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb12ActionPerformed(evt);
            }
        });

        bgLama.add(rb24);
        rb24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb24.setText("24");
        rb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb24ActionPerformed(evt);
            }
        });

        bgLama.add(rb36);
        rb36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb36.setText("36");
        rb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb36ActionPerformed(evt);
            }
        });

        tfAngsur.setEditable(false);
        tfAngsur.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tfBunga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("%");

        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        btnHitung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("bulan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAngsur)
                            .addComponent(tfTotal)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb12)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb24)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb36)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfNama)
                                        .addComponent(cmbMobil, 0, 210, Short.MAX_VALUE)
                                        .addComponent(tfHarga))
                                    .addComponent(tfBunga, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(154, 154, 154))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHitung)
                .addGap(223, 223, 223))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb12)
                    .addComponent(rb24)
                    .addComponent(rb36)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAngsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMobilActionPerformed
        // TODO add your handling code here:
        if(cmbMobil.getSelectedItem()== "Avanza") {
            tfHarga.setText("150000000");
        }else if(cmbMobil.getSelectedItem()== "City") {
            tfHarga.setText("250000000");
        }else if(cmbMobil.getSelectedItem()== "Alphard") {
            tfHarga.setText("500000000");
        }
    }//GEN-LAST:event_cmbMobilActionPerformed

    private void rb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb12ActionPerformed
        // TODO add your handling code here:
        int Harga = Integer.parseInt(tfHarga.getText());
        int Angsur = Harga/12;
        tfAngsur.setText(""+Angsur);
    }//GEN-LAST:event_rb12ActionPerformed

    private void rb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb24ActionPerformed
        // TODO add your handling code here:
        int Harga = Integer.parseInt(tfHarga.getText());
        int Angsur = Harga/24;
        tfAngsur.setText(""+Angsur);
    }//GEN-LAST:event_rb24ActionPerformed

    private void rb36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb36ActionPerformed
        // TODO add your handling code here:
        int Harga = Integer.parseInt(tfHarga.getText());
        int Angsur = Harga/36;
        tfAngsur.setText(""+Angsur);
    }//GEN-LAST:event_rb36ActionPerformed

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int BesarAngsur = Integer.parseInt(tfAngsur.getText());
        int Bunga = Integer.parseInt(tfBunga.getText());
        int TotalAngsuran = BesarAngsur + (BesarAngsur * Bunga/100);
        tfTotal.setText(""+TotalAngsuran);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        tfNama.setText(tabModel.getValueAt(row, 0).toString());
        if(tabModel.getValueAt(row, 1).equals("Avanza")){
            cmbMobil.setSelectedIndex(1);
        }else if(tabModel.getValueAt(row, 1).equals("City")){
            cmbMobil.setSelectedIndex(2);
        }else if(tabModel.getValueAt(row, 1).equals("Alphard")){
            cmbMobil.setSelectedIndex(3);
        }
        tfHarga.setText(tabModel.getValueAt(row, 2).toString());
        if(tabModel.getValueAt(row, 3).equals("12")){
            rb12.setSelected(true);
        }else if(tabModel.getValueAt(row, 3).equals("24")){
            rb24.setSelected(true);
        }else if(tabModel.getValueAt(row, 3).equals("36")){
            rb36.setSelected(true);
        }
        tfAngsur.setText(tabModel.getValueAt(row, 4).toString());
        tfBunga.setText(tabModel.getValueAt(row, 5).toString());
        tfTotal.setText(tabModel.getValueAt(row, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "insert into mobil values " + "(?,?,?,?,?,?,?)";
            prestat = konek.prepareStatement(sql);
            prestat.setString(1,tfNama.getText());
            prestat.setString(2,cmbMobil.getSelectedItem().toString());
            prestat.setString(3,tfHarga.getText());
            String lama = "";
            if(rb12.isSelected()){
                lama = "12";
            }else if(rb24.isSelected()){
                lama = "24";
            }else if(rb36.isSelected()){
                lama = "36";
            }
            prestat.setString(4,lama);
            prestat.setString(5,tfAngsur.getText());
            prestat.setString(6,tfBunga.getText());
            prestat.setString(7,tfTotal.getText());
            prestat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data telah disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            hapusPadaForm();
            tampilDatakeTabel();
            clear();
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "update mobil set mobil=?, "
            + "harga=?, lama=?, besar=?, "
            + "bunga=?, total=? "
            + "where nama=?";
            prestat = konek.prepareStatement(sql);
            prestat.setString(1,cmbMobil.getSelectedItem().toString());
            prestat.setString(2,tfHarga.getText());
            String lama = "";
            if(rb12.isSelected()){
                lama = "12";
            }else if(rb24.isSelected()){
                lama = "24";
            }else if(rb36.isSelected()){
                lama = "36";
            }
            prestat.setString(3,lama);
            prestat.setString(4,tfAngsur.getText());
            prestat.setString(5,tfBunga.getText());
            prestat.setString(6,tfTotal.getText());
            prestat.setString(7,tfNama.getText());
            prestat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            hapusPadaForm();
            tampilDatakeTabel();
            clear();
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "delete from mobil where nama=?";
            prestat = konek.prepareStatement(sql);
            prestat.setString(1,tfNama.getText());
            prestat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data telah dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            hapusPadaForm();
            tampilDatakeTabel();
            clear();
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreditMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreditMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreditMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreditMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KreditMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgLama;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox cmbMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb24;
    private javax.swing.JRadioButton rb36;
    private javax.swing.JTextField tfAngsur;
    private javax.swing.JTextField tfBunga;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
